import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { imageAsset } from '../raster/silhouette';
import type { Asset, Mode } from '../types/geometry';
import './style.css';
type LocalAsset = Asset & { file: File; url: string };
const supported = /\.(svg|png|jpe?g)$/i;
type Rasterized = { data: ImageData; previewUrl: string };
async function pixels(file: File): Promise<Rasterized> { const url = URL.createObjectURL(file), image = new Image(); try { image.src = url; await image.decode(); const scale = Math.min(1, 768 / Math.max(image.naturalWidth, image.naturalHeight)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.naturalWidth * scale)); canvas.height = Math.max(1, Math.round(image.naturalHeight * scale)); const context = canvas.getContext('2d', { willReadFrequently: true })!; context.drawImage(image, 0, 0, canvas.width, canvas.height); const data = context.getImageData(0, 0, canvas.width, canvas.height); const preview = await new Promise<Blob>((resolve, reject) => canvas.toBlob(blob => blob ? resolve(blob) : reject(new Error('Unable to create safe preview')), 'image/png')); return { data, previewUrl: URL.createObjectURL(preview) }; } finally { URL.revokeObjectURL(url); } }
function App() { const [assets, setAssets] = useState<LocalAsset[]>([]), [selected, setSelected] = useState(0), [mode, setMode] = useState<Mode>('auto'), [showImage, setShowImage] = useState(true), [showGeometry, setShowGeometry] = useState(true), [busy, setBusy] = useState(false), [progress, setProgress] = useState(''); const asset = assets[selected];
  const scan = async (event: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []).filter(file => supported.test(file.name)); setBusy(true); setAssets([]); setSelected(0); try { const mapped: LocalAsset[] = []; for (let index = 0; index < files.length; index++) { const file = files[index], source = (file as File & { webkitRelativePath?: string }).webkitRelativePath || file.name, label = file.name.replace(/\.[^/.]+$/, ''); setProgress(`Processing ${index + 1} / ${files.length}: ${file.name}`); try { const raster = await pixels(file); mapped.push({ ...imageAsset(source, raster.data, mode), file, url: raster.previewUrl }); } catch (error) { mapped.push({ id: source.replace(/\.[^/.]+$/, ''), source, label, file, url: '', metadata: { automatic: true, status: 'FAILED', reason: `Could not process image: ${error instanceof Error ? error.message : String(error)}` } }); } setAssets([...mapped]); await new Promise<void>(resolve => setTimeout(resolve, 0)); } setProgress(`Processed ${mapped.length} image${mapped.length === 1 ? '' : 's'}`); } finally { setBusy(false); event.target.value = ''; } };
  const regenerate = async () => { if (!asset) return; setBusy(true); try { URL.revokeObjectURL(asset.url); const raster = await pixels(asset.file); setAssets(previous => previous.map((item, index) => index === selected ? { ...imageAsset(item.source, raster.data, mode), file: item.file, url: raster.previewUrl } : item)); } finally { setBusy(false); } };
  const download = () => { const catalog = { version: '1.1', generatedAt: new Date().toISOString(), settings: { geometryMode: mode, coordinateSystem: 'normalized', orthogonalOnly: true }, assets: assets.map(({ file, url, ...item }) => item) }; const url = URL.createObjectURL(new Blob([JSON.stringify(catalog, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'catalog.json'; link.click(); URL.revokeObjectURL(url); };
  const overlay = useMemo(() => { if (!asset?.geometry) return null; const g = asset.geometry; return g.type === 'rectangle' ? <rect x={g.x} y={g.y} width={g.width} height={g.height} /> : <polygon points={g.points.map(point => point.join(',')).join(' ')} />; }, [asset]);
  return <main><header><h1>Image Shape Annotator</h1><label>Files <input type="file" accept=".svg,.png,.jpg,.jpeg,image/svg+xml,image/png,image/jpeg" multiple disabled={busy} onChange={scan} /></label><label>Folder <input type="file" accept=".svg,.png,.jpg,.jpeg,image/svg+xml,image/png,image/jpeg" multiple disabled={busy} {...({ webkitdirectory: '' } as object)} onChange={scan} /></label><select value={mode} disabled={busy} onChange={event => setMode(event.target.value as Mode)}><option value="auto">auto (orthogonal contour)</option><option value="rectangle">bounding rectangle</option><option value="orthogonal">orthogonal contour</option></select><button onClick={download} disabled={!assets.length}>Export catalog</button></header><section><aside><b>Images ({assets.length})</b><small>{progress}</small>{assets.map((item, index) => <button className={index === selected ? 'active' : ''} key={item.source} onClick={() => setSelected(index)}>{item.label}<small>{item.metadata.status}</small></button>)}</aside><article>{asset ? <><div className="toggles"><label><input checked={showImage} onChange={event => setShowImage(event.target.checked)} type="checkbox" /> Image</label><label><input checked={showGeometry} onChange={event => setShowGeometry(event.target.checked)} type="checkbox" /> Annotation</label><button onClick={regenerate} disabled={busy}>{busy ? 'Processing…' : 'Regenerate'}</button></div><div className="stage">{showImage && <img src={asset.url} />}{showGeometry && <svg viewBox="0 0 1 1" preserveAspectRatio="xMidYMid meet">{overlay}<text x="0.01" y="0.04">{asset.label}</text></svg>}</div><p>{asset.geometry?.type ?? 'No geometry'} · label: {asset.label} · {asset.metadata.status}{asset.metadata.reason ? ` · ${asset.metadata.reason}` : ''}</p></> : <p>Choose individual files or a folder containing SVG, PNG, or JPEG files.</p>}</article><pre>{asset ? JSON.stringify({ label: asset.label, geometry: asset.geometry, metadata: asset.metadata }, null, 2) : 'Generated annotation JSON appears here.'}</pre></section></main>; }
createRoot(document.getElementById('root')!).render(<App />);
