import type { Bounds } from '../types/geometry.js';
type Matrix=[number,number,number,number,number,number]; const I:Matrix=[1,0,0,1,0,0];
const n=(v:string|undefined,d=0)=>Number.parseFloat(v??'')||d;
const attr=(s:string,k:string)=>new RegExp(`\\b${k}\\s*=\\s*["']([^"']*)["']`,'i').exec(s)?.[1];
function mul(a:Matrix,b:Matrix):Matrix{return[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]]}
function transform(s:string|undefined):Matrix { let m=I; for(const x of (s??'').matchAll(/(translate|scale|rotate|matrix)\s*\(([^)]*)\)/gi)){const v=x[2].match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/gi)?.map(Number)??[];let q:Matrix=I;if(x[1].toLowerCase()==='translate')q=[1,0,0,1,v[0]??0,v[1]??0];if(x[1].toLowerCase()==='scale')q=[v[0]??1,0,0,v[1]??v[0]??1,0,0];if(x[1].toLowerCase()==='matrix'&&v.length===6)q=v as Matrix;if(x[1].toLowerCase()==='rotate'){const r=(v[0]??0)*Math.PI/180,c=Math.cos(r),z=Math.sin(r),cx=v[1]??0,cy=v[2]??0;q=mul(mul([1,0,0,1,cx,cy],[c,z,-z,c,0,0]),[1,0,0,1,-cx,-cy]);}m=mul(m,q)} return m }
function pathPoints(d:string){ const out:[number,number][]=[]; let x=0,y=0; for(const match of d.matchAll(/([a-zA-Z])([^a-zA-Z]*)/g)){const cmd=match[1], vs=match[2].match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/gi)?.map(Number)??[]; for(let i=0;i+1<vs.length;i+=cmd.toLowerCase()==='h'||cmd.toLowerCase()==='v'?1:2){let X=x,Y=y;if(cmd.toLowerCase()==='h')X=cmd==='h'?x+vs[i]:vs[i];else if(cmd.toLowerCase()==='v')Y=cmd==='v'?y+vs[i]:vs[i];else {X=cmd===cmd.toLowerCase()?x+vs[i]:vs[i];Y=cmd===cmd.toLowerCase()?y+vs[i+1]:vs[i+1]} x=X;y=Y;out.push([x,y]);}} return out }
export function visibleBounds(svg:string):Bounds|undefined { if(!/<svg\b/i.test(svg)) throw Error('Not an SVG'); const pts:[number,number][]=[]; const tag=/<(rect|line|polygon|polyline|circle|ellipse|path)\b[^>]*>/gi; let m:RegExpExecArray|null; while(m=tag.exec(svg)){const s=m[0];if(/display\s*=\s*["']none|visibility\s*=\s*["']hidden/i.test(s))continue;let p:[number,number][]=[];const name=m[1].toLowerCase();if(name==='rect'){const x=n(attr(s,'x')),y=n(attr(s,'y')),w=n(attr(s,'width')),h=n(attr(s,'height'));p=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]]}else if(name==='line')p=[[n(attr(s,'x1')),n(attr(s,'y1'))],[n(attr(s,'x2')),n(attr(s,'y2'))]];else if(name==='polygon'||name==='polyline'){const q=attr(s,'points')?.match(/[-+]?\d*\.?\d+/g)?.map(Number)??[];for(let i=0;i+1<q.length;i+=2)p.push([q[i],q[i+1]])}else if(name==='circle'||name==='ellipse'){const cx=n(attr(s,'cx')),cy=n(attr(s,'cy')),rx=n(attr(s,name==='circle'?'r':'rx')),ry=n(attr(s,name==='circle'?'r':'ry'));p=[[cx-rx,cy-ry],[cx+rx,cy+ry]]}else p=pathPoints(attr(s,'d')??'');const t=transform(attr(s,'transform'));pts.push(...p.map(([x,y])=>[t[0]*x+t[2]*y+t[4],t[1]*x+t[3]*y+t[5]] as [number,number])); }
 if(!pts.length){const vb=attr(svg,'viewBox')?.trim().split(/[ ,]+/).map(Number);if(vb&&vb.length===4&&vb[2]>0&&vb[3]>0)return{minX:vb[0],minY:vb[1],maxX:vb[0]+vb[2],maxY:vb[1]+vb[3],width:vb[2],height:vb[3]};return undefined} const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys); return {minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY}; }
